// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnUNGRq_0YgcB724DPFicVfJHMunU9C4',
    appId: '1:1069552199662:android:919e60b997aa2e3b7f90ff',
    messagingSenderId: '1069552199662',
    projectId: 'projectmanagerapp-1a953',
    storageBucket: 'projectmanagerapp-1a953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5zL0WED4Lm9yVYTSzzdkhw7gNH1Xa0s',
    appId: '1:1069552199662:ios:cf0e7fefd8aa4c1b7f90ff',
    messagingSenderId: '1069552199662',
    projectId: 'projectmanagerapp-1a953',
    storageBucket: 'projectmanagerapp-1a953.firebasestorage.app',
    iosBundleId: 'com.example.projectManagerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCa9dhCxums9CCbvE0Ii_jpNOZHqn3upNI",
      authDomain: "projectmanagerapp-1a953.firebaseapp.com",
      projectId: "projectmanagerapp-1a953",
      storageBucket: "projectmanagerapp-1a953.firebasestorage.app",
      messagingSenderId: "1069552199662",
      appId: "1:1069552199662:web:74cc2bf2559701e17f90ff",
      measurementId: "G-B8V3DWYNY1"
  );

}

///
/// Sample Login Details :-
/// email : 'admin@gmail.com' &&  pass : 'admin@123'.
/// email : 'danishtp11@gmail.com' &&  pass : 'Danish@1234'.
///

